FROM alpine:3.19.8 AS builder

RUN apk add --update --no-cache ca-certificates


FROM alpine:3.19.8

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ARG BUILD_DIR
ARG BINARY_NAME

COPY $BUILD_DIR/$BINARY_NAME /app

CMD ["/app"]
